/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import estoque.EstoqueCliente;
import estoque.Produto;

/**
 *
 * @author melis
 */
public class Carrinho extends javax.swing.JFrame {

    private EstoqueCliente estoqueCliente;
    private String secao;
    private DefaultListModel<String> listModel;
    private double total;

    private java.util.Map<String, Integer> quantProduto;

    public Carrinho(EstoqueCliente estoqueCliente, String secao) {
        this.estoqueCliente = estoqueCliente;
        this.secao = secao;
        this.quantProduto = new java.util.HashMap<>();
        initComponents();
        atualizarCarrinho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        precoTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        sair = new javax.swing.JButton();
        pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrinho");

        jPanel1.setBackground(new java.awt.Color(255, 235, 211));

        voltar.setBackground(new java.awt.Color(255, 149, 57));
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarVoltar(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 160, 78));
        jLabel2.setText("Valor a pagar:");

        precoTotal.setBackground(new java.awt.Color(255, 235, 211));
        precoTotal.setForeground(new java.awt.Color(204, 160, 78));
        precoTotal.setText("00,00");

        jLabel1.setForeground(new java.awt.Color(204, 160, 78));
        jLabel1.setText("Lista de compras:");

        jScrollPane1.setForeground(new java.awt.Color(204, 160, 78));

        jList1.setBackground(new java.awt.Color(255, 235, 211));
        jList1.setForeground(new java.awt.Color(204, 160, 78));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        sair.setBackground(new java.awt.Color(255, 149, 57));
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        pagar.setBackground(new java.awt.Color(255, 149, 57));
        pagar.setForeground(new java.awt.Color(255, 255, 255));
        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarSeguir(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sair)
                        .addGap(18, 18, 18)
                        .addComponent(pagar))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair)
                    .addComponent(voltar)
                    .addComponent(pagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void adicionarItem(String codigo, int quantidade) {
        int atual = quantProduto.getOrDefault(codigo, 0);
        quantProduto.put(codigo, atual + quantidade);
        atualizarCarrinho();
    }

    private void atualizarCarrinho() {
        listModel = new DefaultListModel<>();
        total = 0.0;
        List<Produto> produtos = estoqueCliente.getProdutos(secao);
        for (String codigo : quantProduto.keySet()) {
            for (Produto p : produtos) {
                if (p.getCodigo().equals(codigo)) {
                    int qtd = quantProduto.get(codigo);
                    double subtotal = qtd * p.getPreco();
                    total += subtotal;
                    listModel.addElement(p.getCodigo() + " - " + p.getNome() + " x " + qtd + " = " + subtotal);
                    break;
                }
            }
        }
        jList1.setModel(listModel);
        precoTotal.setText("Total: " + total);
    }

    private void pagarSeguir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarSeguir
         boolean sucesso = true;
        for (String codigo : quantProduto.keySet()) {
            int qtd = quantProduto.get(codigo);
            boolean comprou = estoqueCliente.comprarProduto(secao, codigo, qtd);
            if (!comprou) {
                sucesso = false;
                JOptionPane.showMessageDialog(this, "Erro na compra do produto: " + codigo);
                break;
            }
        }
        if (sucesso) {
            try {
                estoqueCliente.save();
                JOptionPane.showMessageDialog(this, "Compra finalizada com sucesso!");
                quantProduto.clear();
                atualizarCarrinho();
                new BemVindo().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o estoque!");
            }
        }
    }//GEN-LAST:event_pagarSeguir

    private void voltarVoltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarVoltar
        new AdicionarNoCarrinho(estoqueCliente, secao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarVoltar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pagar;
    private javax.swing.JTextField precoTotal;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
