/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import estoque.EstoqueAdmin;

/**
 *
 * @author melis
 */
public class Escolher extends javax.swing.JFrame {

    EstoqueAdmin estoqueAdmin;
    String secao;

    public Escolher(EstoqueAdmin estoqueAdmin, String secao) {
        this.estoqueAdmin = estoqueAdmin;
        this.secao = secao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        conferir = new javax.swing.JRadioButton();
        adicionar = new javax.swing.JRadioButton();
        mudarPreco = new javax.swing.JRadioButton();
        seguir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolher Ação");

        jPanel1.setBackground(new java.awt.Color(255, 235, 211));

        jLabel1.setForeground(new java.awt.Color(204, 160, 78));
        jLabel1.setText("Informe o que deseja fazer:");

        conferir.setForeground(new java.awt.Color(204, 160, 78));
        conferir.setText("Conferir estoque");
        conferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferirActionPerformed(evt);
            }
        });

        adicionar.setForeground(new java.awt.Color(204, 160, 78));
        adicionar.setText("Adicionar produto");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        mudarPreco.setForeground(new java.awt.Color(204, 160, 78));
        mudarPreco.setText("Mudar preço do produto");
        mudarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarPrecoActionPerformed(evt);
            }
        });

        seguir.setBackground(new java.awt.Color(255, 149, 57));
        seguir.setForeground(new java.awt.Color(255, 255, 255));
        seguir.setText("Seguir");
        seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirSeguir(evt);
            }
        });

        voltar.setBackground(new java.awt.Color(255, 149, 57));
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarVoltar(evt);
            }
        });

        sair.setBackground(new java.awt.Color(255, 149, 57));
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seguir))
                            .addComponent(mudarPreco)
                            .addComponent(adicionar)
                            .addComponent(conferir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mudarPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguir)
                    .addComponent(sair)
                    .addComponent(voltar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarVoltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarVoltar
        new EscolherSecao(estoqueAdmin, null).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarVoltar

    private void seguirSeguir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirSeguir
        if (adicionar.isSelected()) {
            new AdicionarProduto(estoqueAdmin, secao).setVisible(true);
        } else if (conferir.isSelected()) {
            new Conferir(estoqueAdmin, secao).setVisible(true);
        } else if (mudarPreco.isSelected()) {
            new MudarPreco(estoqueAdmin, secao).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_seguirSeguir

    private void mudarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarPrecoActionPerformed
        if (mudarPreco.isSelected()) {
            conferir.setSelected(false);
            adicionar.setSelected(false);
        }
    }//GEN-LAST:event_mudarPrecoActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        if (adicionar.isSelected()) {
            conferir.setSelected(false);
            mudarPreco.setSelected(false);
        }
    }//GEN-LAST:event_adicionarActionPerformed

    private void conferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferirActionPerformed
        if (conferir.isSelected()) {
            adicionar.setSelected(false);
            mudarPreco.setSelected(false);
        }
    }//GEN-LAST:event_conferirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adicionar;
    private javax.swing.JRadioButton conferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mudarPreco;
    private javax.swing.JButton sair;
    private javax.swing.JButton seguir;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
